language: go
go:
  - 1.2
install:
  - go get -v -t ./...
  - mkdir -p $HOME/gopath/bin
  - go install
script:
  - export PATH=$HOME/gopath/bin:$PATH
  - go test ./...
after_script:
  - ./generate-pkgs
deploy:
  provider: releases
  api_key:
    secure: PJ7v7kpUqoD79MraUNgnE/G/V1kkBAVF8D4FPJ6FPScfA/avionrK67UHMcUFiVbj7IaXRsngCFBCq/9NnaHOEuctkoqmytpA5tbMrEsT4oi4L4n8rzAyaX+B8QbgQ4/xiHxmq8kDz5f5YOmkH7AQSqVnM2YpK3B9gc5Je41gpg=
  file:
    - credulous*.deb
    - credulous*.rpm
  on:
    repo: realestate-com-au/credulous
