language: go

go:
  - 1.2

install:
  - go get launchpad.net/goamz/aws
  - go get -v -t ./... 
  - mkdir -p $HOME/gopath/bin
  - go install
  - ./generate-pkgs

script:
 - export PATH=$HOME/gopath/bin:$PATH
 - go test ./...
